export type EmailDataProps = (typeof EMAILS)[0];
export const EMAILS = [
  {
    id: "1",
    name: "João Paulo Duarte",
    avatar: "https://mighty.tools/mockmind-api/content/human/65.jpg",
    marker: "importante",
    subject: "What is Lorem Ipsum?",
    message: "is simply dummy text of the printing and typesetting industry. ",
    start: false,
    date: "12 fev",
  },
  {
    id: "2",
    avatar: "https://mighty.tools/mockmind-api/content/human/44.jpg",
    name: "Bruna",
    subject: "Where does it come from?",
    message:
      "Contrary to popular belief, Lorem Ipsum is not simply random text",
    start: true,
    date: "12 fev",
  },
  {
    id: "3",
    name: "Felipe",
    avatar: "https://mighty.tools/mockmind-api/content/human/57.jpg",
    subject: "Why do we use it?",
    message:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    start: false,
    date: "12 fev",
  },
  {
    id: "4",
    name: "Vitor Lacerda",
    avatar: "https://mighty.tools/mockmind-api/content/human/5.jpg",
    marker: "importante",
    subject: "Where can I get some?",
    message: "There are many variations of passages of Lorem Ipsum available",
    start: true,
    date: "12 fev",
  },
  {
    id: "5",
    name: "Vitor Lacerda",
    avatar: "https://mighty.tools/mockmind-api/content/human/5.jpg",
    marker: "importante",
    subject: "Where can I get some?",
    message: "There are many variations of passages of Lorem Ipsum available",
    start: true,
    date: "12 fev",
  },
  {
    id: "6",
    name: "Vitor Lacerda",
    avatar: "https://mighty.tools/mockmind-api/content/human/5.jpg",
    marker: "importante",
    subject: "Where can I get some?",
    message: "There are many variations of passages of Lorem Ipsum available",
    start: true,
    date: "12 fev",
  },
  {
    id: "7",
    name: "Vitor Lacerda",
    avatar: "https://mighty.tools/mockmind-api/content/human/5.jpg",
    marker: "importante",
    subject: "Where can I get some?",
    message: "There are many variations of passages of Lorem Ipsum available",
    start: true,
    date: "12 fev",
  },
  {
    id: "8",
    name: "Vitor Lacerda",
    avatar: "https://mighty.tools/mockmind-api/content/human/5.jpg",
    marker: "importante",
    subject: "Where can I get some?",
    message: "There are many variations of passages of Lorem Ipsum available",
    start: true,
    date: "12 fev",
  },
  {
    id: "9",
    name: "Vitor Lacerda",
    avatar: "https://mighty.tools/mockmind-api/content/human/5.jpg",
    marker: "importante",
    subject: "Where can I get some?",
    message: "There are many variations of passages of Lorem Ipsum available",
    start: true,
    date: "12 fev",
  },
  {
    id: "10",
    name: "Vitor Lacerda",
    avatar: "https://mighty.tools/mockmind-api/content/human/5.jpg",
    marker: "importante",
    subject: "Where can I get some?",
    message: "There are many variations of passages of Lorem Ipsum available",
    start: true,
    date: "12 fev",
  },
  {
    id: "11",
    name: "Vitor Lacerda",
    avatar: "https://mighty.tools/mockmind-api/content/human/5.jpg",
    marker: "importante",
    subject: "Where can I get some?",
    message: "There are many variations of passages of Lorem Ipsum available",
    start: true,
    date: "12 fev",
  },
  {
    id: "12",
    name: "Vitor Lacerda",
    avatar: "https://mighty.tools/mockmind-api/content/human/5.jpg",
    marker: "importante",
    subject: "Where can I get some?",
    message: "There are many variations of passages of Lorem Ipsum available",
    start: true,
    date: "12 fev",
  },
  {
    id: "13",
    name: "Vitor Lacerda",
    avatar: "https://mighty.tools/mockmind-api/content/human/5.jpg",
    marker: "importante",
    subject: "Where can I get some?",
    message: "There are many variations of passages of Lorem Ipsum available",
    start: true,
    date: "12 fev",
  },
  {
    id: "14",
    name: "Vitor Lacerda",
    avatar: "https://mighty.tools/mockmind-api/content/human/5.jpg",
    marker: "importante",
    subject: "Where can I get some?",
    message: "There are many variations of passages of Lorem Ipsum available",
    start: true,
    date: "12 fev",
  },
  {
    id: "15",
    name: "Vitor Lacerda",
    avatar: "https://mighty.tools/mockmind-api/content/human/5.jpg",
    marker: "importante",
    subject: "Where can I get some?",
    message: "There are many variations of passages of Lorem Ipsum available",
    start: true,
    date: "12 fev",
  },
  {
    id: "16",
    name: "Vitor Lacerda",
    avatar: "https://mighty.tools/mockmind-api/content/human/5.jpg",
    marker: "importante",
    subject: "Where can I get some?",
    message: "There are many variations of passages of Lorem Ipsum available",
    start: true,
    date: "12 fev",
  },
];
